### ISSUE TITLE
Add a diacriticsSensitive option like vue-text-highlight

### ISSUE THREAD

**Issue by ducmerida** [kawamataryo/vue-word-highlighter#131]
I need to support Vue3, I've previouslly used the vue-text-highlight extension with the diacriticsSensitive option, but I don't see this option on vue-word-highlighter.
Can you add this option please?
vue-text-highlight used the diacritics npm package and the following code for text match:
```
 if (!diacriticsSensitive) {
    strCpy = diacritics.remove(strCpy);
    searchStringCpy = diacritics.remove(searchStringCpy);
  }
```
https://github.com/AlbertLucianto/vue-text-highlight/blob/2e356952f68162e36f21462b22a9fd9ab25c9319/src/utils/indicesOf.js#L42

**Comment by kawamataryo** [comment]
Sorry for the very slow response.
Supported in v1.1.0. Try it.

https://user-images.githubusercontent.com/11070996/194713706-8c39e108-4ae9-4472-9444-b33d91bde911.mp4
https://kawamataryo.github.io/vue-word-highlighter/
