### ISSUE TITLE
Question: Do you please have a Vue2 compiled version that works with CDN / script tag?

### ISSUE THREAD

**Issue by Mashiane** [kawamataryo/vue-word-highlighter#331]
Hi there

Is there a a compiled Vue2 version that one can use via the script tag / cdn?

Thank you so much!

**Comment by kawamataryo** [comment]
Hi.
Sorry. Compiled script is not now.

**Comment by kawamataryo** [comment]
This library was distributed at unpkg.com
Please try it.

https://unpkg.com/vue-word-highlighter@1.1.1/dist/vue-word-highlighter.global.js
