### ISSUE TITLE
感謝🥰

### ISSUE THREAD

**Issue by kazuooooo** [kawamataryo/vue-word-highlighter#454]
特にissueではないですが、こちらのライブラリのおかげで、かんたんにハイライトが実装できました！
大感謝です、ありがとうございます！！

<img width="502" alt="日程調整のNitte" src="https://user-images.githubusercontent.com/6919381/188158609-d465ee11-af8f-4e8b-a935-29e5e31f1ed1.png">

**Comment by kazuooooo** [comment]
Closeしてもらって大丈夫です🙏

**Comment by kawamataryo** [comment]
感想ありがとうございます！！！
開発のモチベーションになります🙌
