### ISSUE TITLE
No highlights in v-html + tag handling broken

### ISSUE THREAD

**Issue by perelin** [kawamataryo/vue-word-highlighter#633]
Hi,

thanks for the super useful library!

Noticed the following strange behaviours. Dont know how much is intended.

* when the source content is inside `<WordHighlighter>` every other HTML tag is breaking the rendering
* when the source content is in `textToHighlight` HTML tags are not rendered
* when the source content is in `v-html` no highlights are marked

Im actually only interested in the v-html behaviour 😀 It would be great to have highlights marked there.

Here is a codesandbox demonstrating all behaviours: https://codesandbox.io/s/flamboyant-hooks-606ros?file=/src/components/HelloWorld.vue:866-881 

```js
<template>
  <div class="hello">
    <h1>intended content</h1>
    <p>
      For a guide and <b>recipes</b> on how to configure / customize <br />this
      project, check out the...
    </p>
    <p>
      <i>WordHighlighter query="configure project" split-by-space="true"</i>
    </p>
    <h1>content inline</h1>
    <p>
      <WordHighlighter query="configure project" split-by-space="true">
        For a guide and <b>recipes</b> on how to configure / customize
        <br />this project, check out the...
      </WordHighlighter>
    </p>
    <h1>content in template variable</h1>
    <p>
      <WordHighlighter query="configure project" split-by-space="true">
        {{ content }}
      </WordHighlighter>
    </p>
    <h1>content in textToHighlight</h1>
    <p>
      <WordHighlighter
        query="configure project"
        split-by-space="true"
        :textToHighlight="content"
      />
    </p>
    <h1>content in v-html</h1>
    <p>
      <WordHighlighter
        query="configure project"
        split-by-space="true"
        v-html="content"
      />
    </p>
  </div>
</template>

<script>
import WordHighlighter from "vue-word-highlighter";

export default {
  name: "HelloWorld",
  components: {
    WordHighlighter,
  },
  props: {
    msg: String,
  },
  data() {
    return {
      content:
        "For a guide and <b>recipes</b> on how to configure / customize <br />this project, check out the...",
    };
  },
};
</script>
```

```js
  "dependencies": {
    "vue": "3.2.45",
    "vue-word-highlighter": "1.1.2"
  },
```

![image](https://user-images.githubusercontent.com/517976/208460471-8f9a8ca2-e4ac-4a3e-8635-052dd8cc9cfa.png)

**Comment by kawamataryo** [comment]
Thanks! I'll look into it.

**Comment by kawamataryo** [comment]
There was a bug in the parsing logic. I’ll fix it, but it will take some time.

**Comment by kawamataryo** [comment]
@perelin 

After researching, I found that the plugin cannot support `v-html` due to its structure.
However, I have added `htmlToHighlight` props that can highlight HTML strings. please use `htmlToHighlight`  instead of `v-html`.

An example is here.
https://codesandbox.io/s/intelligent-river-7mygnd?file=/src/components/HelloWorld.vue

**Comment by kawamataryo** [comment]
> when the source content is inside <WordHighlighter> every other HTML tag is breaking the rendering

The above problem has not yet been resolved. I will continue to fix it.

**Comment by perelin** [comment]
> I've thought about it. Due to my plugin structure, cannot support `v-html`. However, I have added `htmlToHighlight` props that can highlight HTML strings. please use `htmlToHighlight` instead of `v-html`.
> 
> Will this meet your needs? Please try it.

Brilliant! Seems to work like a charm :)

Thanks for putting in the effort and time. Especially during holiday season!

**Comment by kawamataryo** [comment]
In v1.2.2 I have resolved all of the issues you raised.
Here is the reproduction.

https://codesandbox.io/s/flamboyant-grass-ogjopb?file=/src/components/HelloWorld.vue

Thank you for reporting the Issue. Have a happy New Year.

**Comment by perelin** [comment]
Thanks for reacting so quickly!

Happy new year to you as well
